# Generated by Django 3.1.7 on 2021-03-23 12:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyaddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
