# Generated by Django 3.1.7 on 2021-03-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drugs', '0001_initial'),
        ('user_profile', '0002_remove_useraddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prescription',
                                    to='user_profile.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='user_medicine', through='user_profile.Medicines',
                                         to='drugs.Drugs'),
        ),
    ]
