# Generated by Django 3.1.7 on 2021-03-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210323_1336'),
        ('orders', '0002_auto_20210323_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.useraddress'),
            preserve_default=False,
        ),
    ]
